services:
  klipper-kp3s-1:
    image: mkuf/klipper:v0.12.0
    privileged: true
    volumes:
      - /dev:/dev
      - ../data/kp3s-1/config:/opt/printer_data/config
      - ../data/kp3s-1/run:/opt/printer_data/run
      - ../data/kp3s-1/gcode:/opt/printer_data/gcodes

  moonraker-kp3s-1:
    image: mkuf/moonraker:latest
    ports:
      - "7130:7125"
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - ../data/kp3s-1/config:/opt/printer_data/config
      - ../data/kp3s-1/moonraker-db:/opt/printer_data/database
      - ../data/kp3s-1/run:/opt/printer_data/run
      - ../data/kp3s-1/gcode:/opt/printer_data/gcodes

  klipper-kp3s-2:
    image: mkuf/klipper:v0.12.0
    privileged: true
    volumes:
      - /dev:/dev
      - ../data/kp3s-2/config:/opt/printer_data/config
      - ../data/kp3s-2/run:/opt/printer_data/run
      - ../data/kp3s-1/gcode:/opt/printer_data/gcodes

  moonraker-kp3s-2:
    image: mkuf/moonraker:latest
    ports:
      - "7132:7125"
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - ../data/kp3s-2/config:/opt/printer_data/config
      - ../data/kp3s-2/moonraker-db:/opt/printer_data/database
      - ../data/kp3s-2/run:/opt/printer_data/run
      - ../data/kp3s-1/gcode:/opt/printer_data/gcodes

  fluidd:
    image: cadriel/fluidd
    ports:
      - 80:80
    restart: unless-stopped
